/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pablo.rrgomes1
 */
public class Lista extends javax.swing.JFrame {

    public Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avestruz = new javax.swing.JLabel();
        Aguia = new javax.swing.JLabel();
        Burro = new javax.swing.JLabel();
        Borboleta = new javax.swing.JLabel();
        Cachorro = new javax.swing.JLabel();
        Cabra = new javax.swing.JLabel();
        Carneiro = new javax.swing.JLabel();
        Camelo = new javax.swing.JLabel();
        Cobra = new javax.swing.JLabel();
        Coelho = new javax.swing.JLabel();
        Cavalo = new javax.swing.JLabel();
        Elefante = new javax.swing.JLabel();
        Galo = new javax.swing.JLabel();
        Gato = new javax.swing.JLabel();
        Jacare = new javax.swing.JLabel();
        Leao = new javax.swing.JLabel();
        Macaco = new javax.swing.JLabel();
        Porco = new javax.swing.JLabel();
        Pavao = new javax.swing.JLabel();
        Peru = new javax.swing.JLabel();
        Touro = new javax.swing.JLabel();
        Tigre = new javax.swing.JLabel();
        Urso = new javax.swing.JLabel();
        Veado = new javax.swing.JLabel();
        Vaca = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        listaAnimaisLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Do Bicho");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(535, 150));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        Avestruz.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Avestruz.setText("Avestruz");
        Avestruz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Aguia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Aguia.setText("Águia");

        Burro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Burro.setText("Burro");

        Borboleta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Borboleta.setText("Borboleta");

        Cachorro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Cachorro.setText("Cachorro");

        Cabra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Cabra.setText("Cabra");

        Carneiro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Carneiro.setText("Carneiro");

        Camelo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Camelo.setText("Camelo");
        Camelo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cobra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Cobra.setText("Cobra");
        Cobra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Coelho.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Coelho.setText("Coelho");

        Cavalo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Cavalo.setText("Cavalo");
        Cavalo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Elefante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Elefante.setText("Elefante");

        Galo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Galo.setText("Galo");
        Galo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Gato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Gato.setText("Gato");

        Jacare.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jacare.setText("Jacaré");

        Leao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Leao.setText("Leão");

        Macaco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Macaco.setText("Macaco");

        Porco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Porco.setText("Porco");
        Porco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Pavao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Pavao.setText("Pavão");

        Peru.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Peru.setText("Peru");
        Peru.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Touro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Touro.setText("Touro");
        Touro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Tigre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tigre.setText("Tigre");

        Urso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Urso.setText("Urso");

        Veado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Veado.setText("Veado");
        Veado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Vaca.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Vaca.setText("Vaca");

        voltarButton.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        listaAnimaisLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        listaAnimaisLabel.setText("Lista de animais");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Borboleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cachorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Camelo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(Coelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Gato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jacare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Elefante)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Aguia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Burro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Avestruz, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Carneiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cobra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(Cavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Galo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Peru, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Pavao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Porco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Macaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Leao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Veado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Urso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tigre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Touro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaAnimaisLabel)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(listaAnimaisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Touro)
                    .addComponent(Leao)
                    .addComponent(Cavalo)
                    .addComponent(Cabra)
                    .addComponent(Avestruz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aguia)
                    .addComponent(Carneiro)
                    .addComponent(Elefante)
                    .addComponent(Macaco)
                    .addComponent(Tigre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Burro)
                    .addComponent(Cobra)
                    .addComponent(Galo)
                    .addComponent(Porco)
                    .addComponent(Urso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Veado)
                    .addComponent(Pavao)
                    .addComponent(Gato)
                    .addComponent(Camelo)
                    .addComponent(Borboleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Coelho, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Vaca)
                        .addComponent(Peru)
                        .addComponent(Cachorro)
                        .addComponent(Jacare)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        Inicial.inicial();
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aguia;
    private javax.swing.JLabel Avestruz;
    private javax.swing.JLabel Borboleta;
    private javax.swing.JLabel Burro;
    private javax.swing.JLabel Cabra;
    private javax.swing.JLabel Cachorro;
    private javax.swing.JLabel Camelo;
    private javax.swing.JLabel Carneiro;
    private javax.swing.JLabel Cavalo;
    private javax.swing.JLabel Cobra;
    private javax.swing.JLabel Coelho;
    private javax.swing.JLabel Elefante;
    private javax.swing.JLabel Galo;
    private javax.swing.JLabel Gato;
    private javax.swing.JLabel Jacare;
    private javax.swing.JLabel Leao;
    private javax.swing.JLabel Macaco;
    private javax.swing.JLabel Pavao;
    private javax.swing.JLabel Peru;
    private javax.swing.JLabel Porco;
    private javax.swing.JLabel Tigre;
    private javax.swing.JLabel Touro;
    private javax.swing.JLabel Urso;
    private javax.swing.JLabel Vaca;
    private javax.swing.JLabel Veado;
    private javax.swing.JLabel listaAnimaisLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
